version: 0.2

phases:
  install:
    commands:
      - echo Installing Java 21...
      - yum remove -y java
      - amazon-linux-extras enable corretto
      - yum install -y java-21-amazon-corretto-devel
      - java -version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${DEFAULT_IMAGE_REPOSITORY_URI}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Gradle project...
      - ./gradlew clean build -Dspring.profiles.active=cloud
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPOSITORY_URI:latest .
      - docker tag $IMAGE_REPOSITORY_URI:latest $IMAGE_REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE_REPOSITORY_URI:latest
      - docker push $IMAGE_REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'