spring:
  cloud:
    aws:
      region:
        static: {$AWS_REGION}
      parameterstore:
        enabled: true
      s3:
        bucket: {$AWS_S3_BUCKET_NAME}
  config:
    import: aws-parameterstore:/nanuming/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 32MB
  jpa:
    hibernate:
      ddl-auto: validate
redis:
  reservation:
    expiration: 900