spring:
  config:
    import:
      - "sm://"
      - "classpath:application-oauth.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sm://DB_HOST}
    username: ${sm://DB_USER}
    password: ${sm://DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${sm://IOS_CLIENT_ID}
            scope:
              - openid
              - profile
              - email