spring:
  config:
    import:
      "sm://"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sm://TEST_DB_HOST}
    username: ${sm://TEST_DB_PASSWORD}
    password: ${sm://TEST_DB_USER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none