spring:
  config:
    import:
      "sm://"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sm://TEST_DB_HOST}
    username: ${sm://TEST_DB_USER}
    password: ${sm://TEST_DB_PASSWORD}
  data:
    redis:
      repositories:
        enabled: false
      host: ${sm://REDIS_HOST}
      port: ${sm://REDIS_PORT}
      password: ${sm://REDIS_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none