spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${sm://IOS_CLIENT_ID}
            #            redirect-uri: # 추후 작성
            scope:
              - openid
              - email
              - profile