spring:
  config:
    import:
      - "sm://"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sm://DB_HOST}
    username: ${sm://DB_USER}
    password: ${sm://DB_PASSWORD}
  data:
    redis:
      repositories:
        enabled: false
      host: ${sm://REDIS_HOST}
      port: ${sm://REDIS_PORT}
      password: ${sm://REDIS_PASSWORD}
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: create
