spring:
  config:
    import:
      sm://
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sm://projects/1009152157741/secrets/TEST_DB_HOST/versions/2}
    username: ${sm://projects/1009152157741/secrets/TEST_DB_PASSWORD/versions/1}
    password: ${sm://projects/1009152157741/secrets/TEST_DB_USER/versions/1}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none